// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xpdjrfmxnbkpqxhjrfmg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhwZGpyZm14bmJrcHF4aGpyZm1nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1MDc0MDIsImV4cCI6MjA2NTA4MzQwMn0.HUD8kN3tAUK-ci6knZThdxoLhGIReNGM81UipUkmVrc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);